### PR TITLE
graphql in guards

### PR DESCRIPTION
**Pull request by josepaiva94**

### CODE REVIEW

**Comment by ilmimris** [comment]
why this PR is not merge?

**Comment by ferrerojosh** [comment]
> 
> 
> why this PR is not merge?

You closed it, I'll check on it if you somehow closed it by accident.

**Comment by josepaiva94** [comment]
I have ended up not using this library so I have closed the PR. Sorry!

Feel free to comment or accept as is!

**Comment by ferrerojosh** [comment]
Should update this merge with the latest source, if you can't do it, do you mind if I add it myself ?

**Comment by josepaiva94** [comment]
Please check! I've tried to merge new changes.

**Comment by ferrerojosh** [comment]
Should remove changes for package.json

**Review by ferrerojosh — CHANGES_REQUESTED** [review]
Unnecessary changes to package json, would cause build to fail

**Comment by josepaiva94** [comment]
Finally :-) Please, check!

**Review by ferrerojosh — APPROVED** [review]

**Comment by ilmimris** [comment]
thanks, @ferrerojosh 👍. Would you mind releasing this feature to npm, please?

**Comment by ferrerojosh** [comment]
> thanks, @ferrerojosh 👍. Would you mind releasing this feature to npm, please?
Would make a release soon

**Pull request merged**
